import { validateEntryData } from "@/lib/content/entryValidation";
import type { CanonicalSchema, FieldDefinition } from "@/lib/schema/fields/types";

export type PreflightStatus = "pass" | "warning" | "fail" | "skipped";
export type PreflightSeverity = "info" | "warning" | "blocking";
export interface PreflightResult { rule_id: string; category: string; severity: PreflightSeverity; status: PreflightStatus; message: string; field?: string; evidence?: Record<string, unknown>; recommended_action?: string; }
export interface PreflightContext { schema: CanonicalSchema; data: Record<string, unknown>; entryStatus: string; duplicateFields: string[]; missingRelations: string[]; unpublishedRelations: string[]; previewAvailable: boolean; }

const pass = (rule_id: string, category: string, message: string): PreflightResult => ({ rule_id, category, severity: "info", status: "pass", message });
const fail = (rule_id: string, category: string, message: string, field?: string, recommended_action?: string): PreflightResult => ({ rule_id, category, severity: "blocking", status: "fail", message, field, recommended_action });
const warning = (rule_id: string, category: string, message: string, field?: string, recommended_action?: string): PreflightResult => ({ rule_id, category, severity: "warning", status: "warning", message, field, recommended_action });
const present = (value: unknown) => value !== undefined && value !== null && value !== "" && (!Array.isArray(value) || value.length > 0);

export function evaluatePreflight(context: PreflightContext): PreflightResult[] {
  const results: PreflightResult[] = [];
  const validationErrors = validateEntryData(context.schema, context.data);
  results.push(...(validationErrors.length ? validationErrors.map((message) => fail("content.validity", "Content", message, undefined, "Correct the field value and run readiness again.")) : [pass("content.validity", "Content", "Required fields and field formats are valid.")]));
  results.push(...context.duplicateFields.map((field) => fail("content.unique", "Content", `A duplicate value exists for the unique field “${field}”.`, field, "Use a unique value before publishing.")));
  if (!context.duplicateFields.length) results.push(pass("content.unique", "Content", "Unique field values are available."));
  results.push(...context.missingRelations.map((field) => fail("reference.exists", "References", `The related entry in “${field}” no longer exists in this workspace.`, field, "Select an existing entry.")));
  results.push(...context.unpublishedRelations.map((field) => warning("reference.published", "References", `The related entry in “${field}” is not published.`, field, "Publish or replace the dependency before release.")));
  if (!context.missingRelations.length && !context.unpublishedRelations.length) results.push(pass("reference.integrity", "References", "All referenced entries are present and published."));
  results.push(...linkRules(context.schema.fields, context.data));
  results.push(...seoRules(context.schema.fields, context.data));
  results.push(...accessibilityRules(context.schema.fields, context.data));
  results.push(context.entryStatus === "approved" || context.entryStatus === "published" ? pass("workflow.approval", "Approval", "The current draft has passed editorial approval.") : fail("workflow.approval", "Approval", "Editorial approval is required before publishing.", undefined, "Submit the draft for review and obtain an independent approval."));
  results.push(context.previewAvailable ? pass("destination.preview", "Destination Preview", "A secure preview route is available for this revision.") : fail("destination.preview", "Destination Preview", "A preview could not be prepared for this revision.", undefined, "Resolve the preview configuration before publishing."));
  return results;
}

function linkRules(fields: FieldDefinition[], data: Record<string, unknown>): PreflightResult[] { const results: PreflightResult[] = []; for (const field of fields.filter((item) => item.type === "url")) { const value = data[field.key]; if (!present(value)) continue; const url = String(value); if (!/^(https?:\/\/|\/)/i.test(url)) results.push(fail("link.malformed", "Links", `“${field.label}” is not a valid absolute URL or internal route.`, field.key, "Use https:// or an internal route beginning with /.")); else if (/localhost|127\.0\.0\.1/i.test(url)) results.push(fail("link.localhost", "Links", `“${field.label}” points to localhost.`, field.key, "Use the public destination URL.")); else if (/staging|preview\./i.test(url)) results.push(warning("link.staging", "Links", `“${field.label}” appears to point to a staging destination.`, field.key, "Confirm this is intentional before release.")); } return results.length ? results : [pass("link.syntax", "Links", "Configured URL fields have no local or malformed links.")]; }
function seoRules(fields: FieldDefinition[], data: Record<string, unknown>): PreflightResult[] { const results: PreflightResult[] = []; const byKey = new Map(fields.map((field) => [field.key, field])); const title = byKey.get("seo_title") ?? byKey.get("meta_title"); const description = byKey.get("meta_description"); const canonical = byKey.get("canonical_url"); const social = byKey.get("social_image"); if (title) { const value = String(data[title.key] ?? ""); if (!value) results.push(warning("seo.title", "SEO", "SEO title is missing.", title.key, "Add a concise page title.")); else if (value.length > 60) results.push(warning("seo.title_length", "SEO", "SEO title exceeds 60 characters.", title.key, "Shorten the title for search-result display.")); } if (description && !present(data[description.key])) results.push(warning("seo.description", "SEO", "Meta description is missing.", description.key, "Add a descriptive meta summary.")); if (canonical && !present(data[canonical.key])) results.push(warning("seo.canonical", "SEO", "Canonical URL is missing.", canonical.key, "Set the canonical destination URL.")); if (social && !present(data[social.key])) results.push(warning("seo.social_image", "SEO", "Social sharing image is missing.", social.key, "Select a social image.")); return results.length ? results : [pass("seo.metadata", "SEO", "No configured SEO metadata is missing.")]; }
function accessibilityRules(fields: FieldDefinition[], data: Record<string, unknown>): PreflightResult[] { const results: PreflightResult[] = []; const media = fields.filter((field) => field.type === "media"); const alt = fields.filter((field) => /(^|_)(alt|alt_text|image_alt)$/i.test(field.key)); for (const field of media.filter((item) => present(data[item.key]))) { if (alt.length && !alt.some((candidate) => present(data[candidate.key]))) results.push(warning("a11y.image_alt", "Accessibility", `Media field “${field.label}” has no supplied alternative text.`, field.key, "Add useful image alternative text.")); } return results.length ? results : [pass("a11y.metadata", "Accessibility", "No detectable accessibility metadata is missing.")]; }
