import { createHash, randomBytes } from "node:crypto";
import { createServiceRoleClient } from "@/lib/admin/serviceRole";
import { getEntry } from "@/lib/content/entryService";
import { logPlatformEvent } from "@/lib/platform/audit";
const hash = (token: string) => createHash("sha256").update(token).digest("hex");
export async function createPreviewToken(params: { workspaceId: string; entryId: string; actorId: string; expiresInHours?: number }) { const entry = await getEntry(params.workspaceId, params.entryId); if (!entry?.current_draft_version_id) throw new Error("Entry draft not found"); const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + Math.min(Math.max(params.expiresInHours ?? 24, 1), 168) * 3_600_000).toISOString(); const db = createServiceRoleClient(); const { error } = await db.from("preview_tokens").insert({ workspace_id: params.workspaceId, entry_id: entry.id, entry_version_id: entry.current_draft_version_id, token_hash: hash(token), expires_at: expiresAt, created_by: params.actorId }); if (error) throw new Error(error.message); await logPlatformEvent({ workspaceId: params.workspaceId, actorAdminUserId: params.actorId, action: "preview.token_created", entityType: "content_entry", entityId: entry.id, metadata: { expiresAt } }); return { token, expiresAt }; }
export async function createReleasePreviewToken(params: { workspaceId: string; releaseId: string; actorId: string; expiresInHours?: number }) { const db = createServiceRoleClient(); const { data: release } = await db.from("releases").select("id, release_items(id)").eq("id", params.releaseId).eq("workspace_id", params.workspaceId).maybeSingle(); if (!release || !(release.release_items ?? []).length) throw new Error("Release not found or has no items"); const token = randomBytes(32).toString("base64url"); const expiresAt = new Date(Date.now() + Math.min(Math.max(params.expiresInHours ?? 24, 1), 168) * 3_600_000).toISOString(); const { error } = await db.from("preview_tokens").insert({ workspace_id: params.workspaceId, release_id: release.id, token_hash: hash(token), expires_at: expiresAt, created_by: params.actorId }); if (error) throw new Error(error.message); await logPlatformEvent({ workspaceId: params.workspaceId, actorAdminUserId: params.actorId, action: "release.preview_token_created", entityType: "release", entityId: release.id, metadata: { expiresAt } }); return { token, expiresAt }; }
export async function resolvePreviewToken(token: string) { const db = createServiceRoleClient(); const { data, error } = await db.from("preview_tokens").select("*, content_entry_versions!preview_tokens_entry_version_id_fkey(*), content_entries!preview_tokens_entry_id_fkey(content_models!content_entries_workspace_model_fk(name, api_key))").eq("token_hash", hash(token)).is("revoked_at", null).gt("expires_at", new Date().toISOString()).maybeSingle(); if (error) throw new Error(`Preview token lookup failed: ${error.message}`); if (!data) return null; await db.from("preview_tokens").update({ last_used_at: new Date().toISOString() }).eq("id", data.id); return data; }
export async function getReleasePreview(workspaceId: string, releaseId: string) { const { data } = await createServiceRoleClient().from("releases").select("id, name, description, release_items(entry_id, entry_version_id, content_entry_versions(data_jsonb, locale, content_entries(content_models(name, api_key))))").eq("workspace_id", workspaceId).eq("id", releaseId).maybeSingle(); return data; }
