import { requireDeveloperApi, developerModelAllowed } from "@/lib/developer/apiAuth";
import { apiError, apiSuccess } from "@/lib/developer/apiContract";
import { getEntryDeveloperView } from "@/lib/developer/resourceService";
import { publishEntry } from "@/lib/content/entryService";
import { runEntryPreflight } from "@/lib/content/preflightService";
import { queueEntryPublication } from "@/lib/content/publicationService";
import { logDeveloperApiMutation } from "@/lib/developer/developerAudit";

export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireDeveloperApi(req,{scope:"content.publish",requireActor:true});if(auth.error)return auth.error;const {id}=await params;const view=await getEntryDeveloperView(auth.data!.workspaceId,id);if(!view)return apiError("ENTRY_NOT_FOUND","Content entry not found",404,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});if(!developerModelAllowed(auth.data!,view.model.apiKey))return apiError("MODEL_RESTRICTED","Token is not permitted to access this content model",403,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});const preflight=await runEntryPreflight(auth.data!.workspaceId,id);if(!preflight)return apiError("ENTRY_NOT_FOUND","Entry or current draft not found",404,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});if(preflight.status==="blocked")return apiError("PREFLIGHT_BLOCKED",`Publish readiness has ${preflight.summary.blocking} blocking issue(s)`,409,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit,details:preflight});const result=await publishEntry({workspaceId:auth.data!.workspaceId,entryId:id,actorAdminUserId:auth.data!.actorAdminUserId!});if(!result.ok)return apiError("PUBLISH_FAILED",result.error,result.status,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});if(result.data.published_version_id)await queueEntryPublication({workspaceId:auth.data!.workspaceId,actorId:auth.data!.actorAdminUserId!,entryId:id,versionId:result.data.published_version_id});await logDeveloperApiMutation(auth.data!,"developer.entry.published","content_entry",id,{model:view.model.apiKey,publishedVersionId:result.data.published_version_id});return apiSuccess({entry:result.data,preflight},{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}
