"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import AdminLayout from "@/components/admin/AdminLayout";
import ReleasePreviewButton from "@/components/admin/ReleasePreviewButton";
import { AlertTriangle, ArrowLeft, CalendarClock, Check, CircleX, Loader2, Rocket, ShieldCheck, UserPlus } from "lucide-react";

type Readiness = { status:"ready"|"blocked"; summary:{blocking:number;warnings:number;items:number;locales:number}; issues:Array<{code:string;severity:"blocking"|"warning";message:string;entryId?:string;locale?:string}>; itemReports:Array<{entryId:string;versionId:string;locale:string;drifted:boolean;preflight?:{summary:{blocking:number;warnings:number}}|null}>; localeReadiness:Array<{locale:string;required:boolean;status:"ready"|"blocked";missingSourceEntryIds:string[]}>; rollbackPlan:Array<{entryId:string;targetVersionId:string;previousPublishedVersionId:string|null}> };
type Release = { id:string;name:string;description:string|null;status:string;scheduled_for:string|null;approved_at:string|null;published_at:string|null;status_reason:string|null;release_items:Array<{id:string;entry_id:string;entry_version_id:string;delivery_status:string;delivery_error:string|null;content_entry_versions?:{locale:string;version_number:number;data_jsonb:Record<string,unknown>}|null;content_entries?:{status:string;content_models?:{name:string;api_key:string}|null}|null}>;release_locale_targets:Array<{locale:string;required:boolean}>;release_assignments:Array<{id:string;assigned_to_admin_user_id:string;role:string;status:string;due_at:string|null;note:string|null}>;release_history:Array<{id:string;action:string;from_status:string|null;to_status:string|null;detail_json:Record<string,unknown>;created_at:string}>;release_rollback_items:Array<{entry_id:string;target_version_id:string;previous_published_version_id:string|null}> };
type Collaborator = { id:string;displayName:string;email:string };

const statusClass:Record<string,string>={draft:"text-fg-secondary",approved:"text-success",scheduled:"text-cyan-300",publishing:"text-warning",published:"text-success",partially_failed:"text-danger",cancelled:"text-fg-muted"};

export default function ReleaseDetailPage(){
  const { id }=useParams<{id:string}>();
  const [release,setRelease]=useState<Release|null>(null); const [readiness,setReadiness]=useState<Readiness|null>(null); const [collaborators,setCollaborators]=useState<Collaborator[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [scheduledFor,setScheduledFor]=useState(""); const [comment,setComment]=useState(""); const [assigneeId,setAssigneeId]=useState(""); const [assignmentRole,setAssignmentRole]=useState<"reviewer"|"approver"|"publisher">("approver"); const [assignmentDue,setAssignmentDue]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [releaseRes,readyRes,peopleRes]=await Promise.all([fetch(`/api/releases/${id}`),fetch(`/api/releases/${id}/readiness`),fetch("/api/workspace/collaborators")]);const [releaseBody,readyBody,peopleBody]=await Promise.all([releaseRes.json(),readyRes.json(),peopleRes.json()]);if(!releaseRes.ok)throw new Error(releaseBody.error||"Could not load release");if(!readyRes.ok)throw new Error(readyBody.error||"Could not evaluate readiness");setRelease(releaseBody.data);setReadiness(readyBody.data);if(peopleRes.ok)setCollaborators(peopleBody.data||[]);if(releaseBody.data?.scheduled_for)setScheduledFor(new Date(releaseBody.data.scheduled_for).toISOString().slice(0,16));}catch(err){setError(err instanceof Error?err.message:"Could not load release");}finally{setLoading(false);}},[id]);
  useEffect(()=>{void load();},[load]);
  const transition=async(action:"approve"|"request_changes"|"schedule"|"cancel")=>{setBusy(action);setError("");setNotice("");try{const res=await fetch(`/api/releases/${id}/transition`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,comment,scheduledFor:action==="schedule"&&scheduledFor?new Date(scheduledFor).toISOString():null})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Release transition failed");setNotice(`Release ${action.replaceAll("_"," ")} completed.`);setComment("");await load();}catch(err){setError(err instanceof Error?err.message:"Release transition failed");}finally{setBusy("");}};
  const publish=async()=>{setBusy("publish");setError("");setNotice("");try{const res=await fetch(`/api/releases/${id}/publish`,{method:"POST"});const body=await res.json();if(!res.ok)throw new Error(body.error||"Could not publish release");setNotice("Pinned release versions were published transactionally.");await load();}catch(err){setError(err instanceof Error?err.message:"Could not publish release");}finally{setBusy("");}};
  const assign=async()=>{if(!assigneeId)return;setBusy("assign");setError("");try{const res=await fetch(`/api/releases/${id}/assignments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assigneeId,role:assignmentRole,dueAt:assignmentDue?new Date(assignmentDue).toISOString():null})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Could not assign release");setNotice("Release assignment created and notification queued.");await load();}catch(err){setError(err instanceof Error?err.message:"Could not assign release");}finally{setBusy("");}};
  if(loading)return <AdminLayout><div className="flex min-h-[60vh] items-center justify-center text-fg-muted"><Loader2 className="animate-spin"/></div></AdminLayout>;
  if(!release)return <AdminLayout><div className="mx-auto max-w-4xl rounded-xl border border-danger p-5 text-danger">{error||"Release not found"}</div></AdminLayout>;
  return <AdminLayout><div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-subtle pb-6"><div className="flex items-start gap-3"><Link href="/admin/releases" className="mt-1 rounded-lg border border-subtle p-2 text-fg-muted"><ArrowLeft size={15}/></Link><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-action">Release operations / {release.id.slice(0,8)}</p><h1 className="mt-1 text-3xl font-extrabold">{release.name}</h1><p className="mt-2 max-w-2xl text-sm text-fg-muted">{release.description||"No release purpose recorded."}</p></div></div><div className="flex items-center gap-3"><ReleasePreviewButton releaseId={release.id}/><span className={`text-xs font-bold uppercase tracking-wider ${statusClass[release.status]||"text-fg-secondary"}`}>{release.status.replaceAll("_"," ")}</span></div></header>
    {error&&<div className="rounded-xl border border-danger bg-danger-muted p-4 text-sm text-danger">{error}</div>}{notice&&<div className="rounded-xl border border-success bg-success-muted p-4 text-sm text-success">{notice}</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,.6fr)]"><main className="space-y-5">
      <section className={`rounded-2xl border p-5 ${readiness?.status==="ready"?"border-success bg-success-muted":"border-danger bg-danger-muted"}`}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-fg-muted">Release readiness</p><h2 className="mt-1 flex items-center gap-2 text-lg font-bold">{readiness?.status==="ready"?<ShieldCheck size={18} className="text-success"/>:<AlertTriangle size={18} className="text-danger"/>}{readiness?.status==="ready"?"Ready for controlled publication":"Blocked"}</h2></div><div className="text-right text-[10px] uppercase tracking-wider text-fg-muted"><div>{readiness?.summary.blocking||0} blockers</div><div>{readiness?.summary.warnings||0} warnings</div></div></div>{readiness?.issues.length?<div className="mt-4 space-y-2">{readiness.issues.map((issue,index)=><div key={`${issue.code}-${index}`} className={`rounded-lg border px-3 py-2 text-xs ${issue.severity==="blocking"?"border-danger text-red-200":"border-warning text-amber-200"}`}><strong className="mr-2 font-mono text-[9px] uppercase opacity-60">{issue.code}</strong>{issue.message}</div>)}</div>:<p className="mt-3 text-xs text-success">Pinned versions, dependencies, approvals and required locales have no blocking readiness findings.</p>}</section>
      <section className="rounded-2xl border border-subtle bg-surface-1 p-5"><h2 className="font-bold">Pinned versions</h2><div className="mt-4 space-y-2">{release.release_items.map((item)=><div key={item.id} className="grid gap-3 rounded-lg border border-subtle bg-field px-3 py-3 sm:grid-cols-[1fr_auto]"><div><Link href={`/admin/entries/${item.entry_id}`} className="font-mono text-xs text-fg-secondary hover:text-fg-primary">entry:{item.entry_id.slice(0,8)}</Link><p className="mt-1 text-[10px] text-fg-muted">version {item.content_entry_versions?.version_number??"?"} · locale {item.content_entry_versions?.locale||"?"} · {item.content_entries?.status||"unknown"}</p></div><span className="text-[10px] font-bold uppercase tracking-wider text-fg-muted">{item.delivery_status}</span></div>)}</div></section>
      <section className="rounded-2xl border border-review bg-review-muted p-5"><h2 className="font-bold">Locale coordination</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{readiness?.localeReadiness.map((locale)=><div key={locale.locale} className="rounded-lg border border-subtle bg-field p-3"><div className="flex items-center justify-between"><span className="font-mono text-sm text-fg-primary">{locale.locale}{locale.required?" · required":""}</span><span className={`text-[10px] font-bold uppercase ${locale.status==="ready"?"text-success":"text-danger"}`}>{locale.status}</span></div>{locale.missingSourceEntryIds.length>0&&<p className="mt-2 text-[10px] text-fg-muted">{locale.missingSourceEntryIds.length} source item(s) lack a current reviewed translation in this bundle.</p>}</div>)}</div></section>
      <section className="rounded-2xl border border-subtle bg-surface-1 p-5"><h2 className="font-bold">Rollback plan</h2><p className="mt-1 text-xs text-fg-muted">Captured at release approval. It records exactly what was published before each target version.</p><div className="mt-4 space-y-2">{(readiness?.rollbackPlan||[]).length?(readiness?.rollbackPlan||[]).map((row)=><div key={row.entryId} className="rounded-lg border border-subtle bg-field px-3 py-2 font-mono text-[10px] text-fg-muted">{row.entryId.slice(0,8)} · target {row.targetVersionId.slice(0,8)} · previous {row.previousPublishedVersionId?.slice(0,8)||"none"}</div>):<p className="text-xs text-fg-muted">Rollback snapshot is created when the release is approved.</p>}</div></section>
      <section className="rounded-2xl border border-subtle bg-surface-1 p-5"><h2 className="font-bold">Release history</h2><div className="mt-4 space-y-2">{release.release_history?.length?release.release_history.map((event)=><div key={event.id} className="flex items-start justify-between gap-4 border-b border-subtle py-2 text-xs last:border-0"><span className="text-fg-secondary">{event.action.replaceAll("_"," ")}{event.from_status||event.to_status?<span className="text-fg-muted"> · {event.from_status||"—"} → {event.to_status||"—"}</span>:null}</span><time className="shrink-0 text-[10px] text-fg-muted">{new Date(event.created_at).toLocaleString()}</time></div>):<p className="text-xs text-fg-muted">No release history yet.</p>}</div></section>
    </main><aside className="space-y-5">
      <section className="rounded-2xl border border-action/20 bg-action/[0.03] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-action">Release gate</p><textarea value={comment} onChange={(e)=>setComment(e.target.value)} rows={2} placeholder="Decision note" className="mt-3 w-full resize-none rounded-lg border border-subtle bg-field px-3 py-2 text-xs text-fg-primary"/>{release.status==="draft"&&<button type="button" disabled={Boolean(busy)||readiness?.status!=="ready"} onClick={()=>void transition("approve")} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-success-muted text-success disabled:opacity-40">{busy==="approve"?<Loader2 size={13} className="animate-spin"/>:<Check size={13}/>} Approve release</button>}{["approved","scheduled"].includes(release.status)&&<button type="button" disabled={Boolean(busy)} onClick={()=>void transition("request_changes")} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg border border-warning px-3 py-2.5 text-xs font-bold uppercase text-warning disabled:opacity-40"><CircleX size={13}/> Request changes</button>}{["approved","scheduled"].includes(release.status)&&<><label className="mt-4 block text-[10px] font-bold uppercase tracking-wider text-fg-muted">Publish date & time<input type="datetime-local" value={scheduledFor} onChange={(e)=>setScheduledFor(e.target.value)} className="mt-2 w-full rounded-lg border border-subtle bg-field px-3 py-2 text-xs text-fg-secondary"/></label><button type="button" disabled={Boolean(busy)||!scheduledFor||readiness?.status!=="ready"} onClick={()=>void transition("schedule")} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg border border-cyan-400/25 px-3 py-2.5 text-xs font-bold uppercase text-cyan-300 disabled:opacity-40"><CalendarClock size={13}/> Schedule</button><button type="button" disabled={Boolean(busy)||readiness?.status!=="ready"||release.status==="scheduled"&&Boolean(release.scheduled_for&&new Date(release.scheduled_for)>new Date())} onClick={()=>void publish()} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg ui-btn ui-btn-primary disabled:opacity-40">{busy==="publish"?<Loader2 size={13} className="animate-spin"/>:<Rocket size={13}/>} Publish pinned versions</button></>}{!["published","cancelled"].includes(release.status)&&<button type="button" disabled={Boolean(busy)} onClick={()=>void transition("cancel")} className="mt-2 w-full rounded-lg border border-danger px-3 py-2 text-[10px] font-bold uppercase text-danger disabled:opacity-40">Cancel release</button>}</section>
      <section className="rounded-2xl border border-subtle bg-surface-1 p-5"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-fg-muted">Assignment</p><h2 className="mt-1 font-bold">Release owner queue</h2><select value={assigneeId} onChange={(e)=>setAssigneeId(e.target.value)} className="mt-4 w-full rounded-lg border border-subtle bg-canvas px-3 py-2 text-xs text-fg-secondary"><option value="">Select collaborator</option>{collaborators.map((person)=><option key={person.id} value={person.id}>{person.displayName} · {person.email}</option>)}</select><select value={assignmentRole} onChange={(e)=>setAssignmentRole(e.target.value as typeof assignmentRole)} className="mt-2 w-full rounded-lg border border-subtle bg-canvas px-3 py-2 text-xs text-fg-secondary"><option value="reviewer">Reviewer</option><option value="approver">Approver</option><option value="publisher">Publisher</option></select><input type="datetime-local" value={assignmentDue} onChange={(e)=>setAssignmentDue(e.target.value)} className="mt-2 w-full rounded-lg border border-subtle bg-canvas px-3 py-2 text-xs text-fg-secondary"/><button type="button" disabled={!assigneeId||Boolean(busy)} onClick={()=>void assign()} className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg border border-subtle px-3 py-2 text-[10px] font-bold uppercase text-fg-secondary disabled:opacity-40"><UserPlus size={12}/> Assign & notify</button><div className="mt-4 space-y-2">{release.release_assignments?.filter((item)=>item.status==="active").map((item)=><div key={item.id} className="rounded-lg border border-subtle bg-field px-3 py-2 text-[10px] text-fg-muted">{collaborators.find((person)=>person.id===item.assigned_to_admin_user_id)?.displayName||item.assigned_to_admin_user_id.slice(0,8)} · <strong className="text-fg-secondary">{item.role}</strong>{item.due_at?` · due ${new Date(item.due_at).toLocaleString()}`:""}</div>)}</div></section>
    </aside></div>
  </div></AdminLayout>;
}
