import { createServiceRoleClient } from "@/lib/admin/serviceRole";
import { requireDeveloperApi, developerModelAllowed } from "@/lib/developer/apiAuth";
import { apiError, apiSuccess } from "@/lib/developer/apiContract";
import { createRelease, listReleases } from "@/lib/content/releaseService";
import { logDeveloperApiMutation } from "@/lib/developer/developerAudit";

async function restrictedVersions(workspaceId:string,versionIds:string[],allowedModels:string[]){if(!allowedModels.length)return [];const {data}=await createServiceRoleClient().from("content_entry_versions").select("id,content_entries!inner(workspace_id,content_models!inner(api_key))").in("id",versionIds).eq("content_entries.workspace_id",workspaceId);return (data??[]).filter((row:any)=>!allowedModels.includes(row.content_entries?.content_models?.api_key)).map((row:any)=>row.id);}
export async function GET(req:Request){const auth=await requireDeveloperApi(req,{scope:"releases.read"});if(auth.error)return auth.error;const releases=await listReleases(auth.data!.workspaceId);if(!auth.data!.allowedModels.length)return apiSuccess(releases,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});const db=createServiceRoleClient();const allowed=new Set(auth.data!.allowedModels);const visible=[];for(const release of releases){const ids=(release.release_items??[]).map((i:any)=>i.entry_id);if(!ids.length){visible.push(release);continue;}const {data}=await db.from("content_entries").select("id,content_models!inner(api_key)").in("id",ids).eq("workspace_id",auth.data!.workspaceId);if((data??[]).every((e:any)=>allowed.has(e.content_models?.api_key)))visible.push(release);}return apiSuccess(visible,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}
export async function POST(req:Request){const auth=await requireDeveloperApi(req,{scope:"releases.write",requireActor:true});if(auth.error)return auth.error;try{const body=await req.json();const versionIds=Array.isArray(body.itemVersionIds)?body.itemVersionIds.map(String):[];const denied=await restrictedVersions(auth.data!.workspaceId,versionIds,auth.data!.allowedModels);if(denied.length)return apiError("MODEL_RESTRICTED","Release contains versions from models outside this token's allowlist",403,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit,details:{versionIds:denied}});const result=await createRelease({workspaceId:auth.data!.workspaceId,actorId:auth.data!.actorAdminUserId!,name:String(body.name||""),description:body.description,itemVersionIds:versionIds,locales:Array.isArray(body.locales)?body.locales.map(String):[]});if(!result.ok)return apiError("RELEASE_CREATE_FAILED",result.error,result.status,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});const id=(result.data as any)?.release_id??(result.data as any)?.id??null;await logDeveloperApiMutation(auth.data!,"developer.release.created","release",id,{name:body.name,itemCount:versionIds.length});return apiSuccess(result.data,{status:201,requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}catch(e){return apiError("RELEASE_CREATE_FAILED",e instanceof Error?e.message:"Could not create release",400,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}}
