import { requireDeveloperApi, developerModelAllowed } from "@/lib/developer/apiAuth";
import { apiError, apiSuccess } from "@/lib/developer/apiContract";
import { createEntry } from "@/lib/content/entryService";
import { getModelByApiKey, listDeveloperEntries } from "@/lib/developer/resourceService";
import { listModels } from "@/lib/schema/modelService";
import { logDeveloperApiMutation } from "@/lib/developer/developerAudit";

export async function GET(req:Request){const auth=await requireDeveloperApi(req,{scope:"content.read"});if(auth.error)return auth.error;try{const url=new URL(req.url),modelApiKey=url.searchParams.get("model")||undefined;if(modelApiKey&&!developerModelAllowed(auth.data!,modelApiKey))return apiError("MODEL_RESTRICTED","Token is not permitted to access this content model",403,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});const result=await listDeveloperEntries({workspaceId:auth.data!.workspaceId,modelApiKey,status:url.searchParams.get("status")||undefined,locale:url.searchParams.get("locale")||undefined,limit:Number(url.searchParams.get("limit")||50),offset:Number(url.searchParams.get("offset")||0)});let rows=result.rows;if(!modelApiKey&&auth.data!.allowedModels.length){const models=await listModels(auth.data!.workspaceId);const allowedIds=new Set(models.filter(m=>auth.data!.allowedModels.includes(m.api_key)).map(m=>m.id));rows=rows.filter((r:any)=>allowedIds.has(r.content_model_id));}return apiSuccess(rows,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit,pagination:{limit:result.limit,offset:result.offset,returned:rows.length}});}catch(e){return apiError("ENTRY_LIST_FAILED",e instanceof Error?e.message:"Could not list entries",400,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}}
export async function POST(req:Request){let body:any;try{body=await req.json();}catch{return apiError("INVALID_JSON","Request body must be JSON",400);}const modelApiKey=String(body.model||"");const auth=await requireDeveloperApi(req,{scope:"content.write",modelApiKey,requireActor:true});if(auth.error)return auth.error;try{const model=await getModelByApiKey(auth.data!.workspaceId,modelApiKey);if(!model)return apiError("MODEL_NOT_FOUND","Active content model not found",404,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});const result=await createEntry({workspaceId:auth.data!.workspaceId,modelId:model.id,data:body.data&&typeof body.data==="object"?body.data:{},locale:body.locale||"en",actorAdminUserId:auth.data!.actorAdminUserId!,changeSummary:body.changeSummary||"Created through Developer API"});if(!result.ok)return apiError("ENTRY_CREATE_FAILED",result.error,result.status,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});await logDeveloperApiMutation(auth.data!,"developer.entry.created","content_entry",result.data.entry.id,{model:modelApiKey,versionId:result.data.version.id});return apiSuccess(result.data,{status:201,requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}catch(e){return apiError("ENTRY_CREATE_FAILED",e instanceof Error?e.message:"Could not create entry",400,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}}
