"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Copy, KeyRound, RefreshCw, ShieldCheck, TerminalSquare, Trash2 } from "lucide-react";
import AdminLayout from "@/components/admin/AdminLayout";
import { getAuthHeaders } from "@/lib/admin/authCheck";

type TokenRow = { id: string; name: string; token_prefix: string; scopes: string[]; allowed_models: string[]; rate_limit_per_minute: number; expires_at: string | null; last_used_at: string | null; revoked_at: string | null; created_at: string };
type ModelRow = { id: string; name: string; api_key: string; status: string };
const scopes = ["content.read","content.write","content.publish","media.read","media.write","schema.read","schema.write","releases.read","releases.write","analytics.read","environment.read","environment.write","connection.read","connection.write","infrastructure.read","infrastructure.write"];

async function authFetch(input: RequestInfo | URL, init: RequestInit = {}) { const auth = await getAuthHeaders(); if (!auth.Authorization) throw new Error("Admin session is unavailable. Please sign in again."); const headers = new Headers(init.headers); for (const [key, value] of Object.entries(auth)) headers.set(key, value); return fetch(input, { ...init, headers }); }
const fmt = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";

export default function DeveloperPlatformPage() {
  const [tokens, setTokens] = useState<TokenRow[]>([]); const [models, setModels] = useState<ModelRow[]>([]); const [openapi, setOpenapi] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [secret, setSecret] = useState("");
  const [name, setName] = useState(""); const [selectedScopes, setSelectedScopes] = useState<string[]>(["content.read","schema.read"]); const [allowedModels, setAllowedModels] = useState<string[]>([]); const [rateLimit, setRateLimit] = useState(120); const [expiresAt, setExpiresAt] = useState("");

  const load = useCallback(async () => { setLoading(true); setError(""); try { const [tokenResponse, modelResponse, openapiResponse] = await Promise.all([authFetch("/api/developer/tokens"),authFetch("/api/models"),authFetch("/api/developer/openapi")]); const [tokenBody, modelBody, openapiBody] = await Promise.all([tokenResponse.json(),modelResponse.json(),openapiResponse.json()]); if (!tokenResponse.ok) throw new Error(tokenBody.error || "Could not load tokens"); if (!modelResponse.ok) throw new Error(modelBody.error || "Could not load models"); if (!openapiResponse.ok) throw new Error(openapiBody.error || "Could not load OpenAPI"); setTokens(tokenBody.data || []); setModels((modelBody.data || []).filter((model: ModelRow) => model.status === "active")); setOpenapi(openapiBody.data || null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load Developer Platform"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const pathCount = useMemo(() => openapi && typeof openapi.paths === "object" && openapi.paths ? Object.keys(openapi.paths as Record<string, unknown>).length : 0, [openapi]);
  const toggle = (value: string, setter: React.Dispatch<React.SetStateAction<string[]>>) => setter((values) => values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  const create = async () => { setBusy(true); setError(""); setSecret(""); try { const response = await authFetch("/api/developer/tokens", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, scopes: selectedScopes, allowedModels, rateLimitPerMinute: rateLimit, expiresAt: expiresAt ? new Date(expiresAt).toISOString() : null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not create token"); setSecret(body.data.secret); setName(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create token"); } finally { setBusy(false); } };
  const revoke = async (id: string) => { setBusy(true); setError(""); try { const response = await authFetch(`/api/developer/tokens/${id}/revoke`, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not revoke token"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not revoke token"); } finally { setBusy(false); } };
  const example = `curl -H "Authorization: Bearer pnv_YOUR_TOKEN" \\
  http://localhost:3000/api/v1/content/${models[0]?.api_key || "blog_post"}?limit=25`;

  return <AdminLayout><div className="ui-page mx-auto max-w-7xl">
    <header className="ui-page-header"><div><p className="ui-eyebrow flex items-center gap-1.5"><TerminalSquare size={12}/>Developer Platform</p><h1 className="ui-page-title">API & Schema Delivery</h1><p className="ui-page-description">Create scoped service credentials and inspect the stable workspace REST/OpenAPI contract. Plaintext token secrets are shown once and are never stored.</p></div><button onClick={() => void load()} disabled={loading} className="ui-btn ui-btn-secondary"><RefreshCw size={14} className={loading ? "animate-spin" : ""}/>Refresh</button></header>
    {error ? <div className="ui-alert ui-alert-danger mt-5">{error}</div> : null}
    {secret ? <div className="ui-alert ui-alert-warning mt-5"><div className="font-semibold">New API secret — copy it now</div><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-lg bg-field p-3 text-xs text-fg-primary">{secret}</code><button onClick={() => void navigator.clipboard.writeText(secret)} className="ui-btn ui-btn-secondary"><Copy size={14}/></button></div><p className="mt-2 text-[11px]">Only its SHA-256 hash is stored. The plaintext cannot be retrieved later.</p></div> : null}

    <section className="ui-section grid gap-10 xl:grid-cols-[1fr_.85fr]">
      <div><div className="flex items-center gap-2"><KeyRound size={16} className="text-icon-secondary"/><h2 className="ui-section-title">Create scoped API token</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="text-[12px] font-medium text-fg-secondary">Name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Production website" className="mt-2 w-full rounded-lg px-3 py-2.5 text-sm"/></label><label><span className="text-[12px] font-medium text-fg-secondary">Requests / minute</span><input type="number" min={1} max={10000} value={rateLimit} onChange={(e) => setRateLimit(Number(e.target.value))} className="mt-2 w-full rounded-lg px-3 py-2.5 text-sm"/></label><label className="sm:col-span-2"><span className="text-[12px] font-medium text-fg-secondary">Expires at (optional)</span><input type="datetime-local" value={expiresAt} onChange={(e) => setExpiresAt(e.target.value)} className="mt-2 w-full rounded-lg px-3 py-2.5 text-sm"/></label></div>
        <h3 className="mt-6 text-[13px] font-semibold text-fg-primary">Scopes</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{scopes.map((scope) => <label key={scope} className="flex items-center gap-2 rounded-lg bg-surface-2 px-3 py-2 text-[12px] text-fg-secondary"><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={() => toggle(scope,setSelectedScopes)} className="accent-primary"/>{scope}</label>)}</div>
        <h3 className="mt-6 text-[13px] font-semibold text-fg-primary">Model restriction</h3><p className="mt-1 text-[11px] text-fg-muted">No selection means all models permitted by the token scopes.</p><div className="mt-3 max-h-48 overflow-auto border-y border-subtle">{models.map((model) => <label key={model.id} className="ui-list-row px-1 text-[12px] text-fg-secondary"><input type="checkbox" checked={allowedModels.includes(model.api_key)} onChange={() => toggle(model.api_key,setAllowedModels)} className="accent-primary"/><span>{model.name}</span><code className="ml-auto text-[10px] text-fg-muted">{model.api_key}</code></label>)}</div>
        <button disabled={busy || !name.trim() || selectedScopes.length === 0} onClick={() => void create()} className="ui-btn ui-btn-primary mt-5 disabled:opacity-40">Create token</button>
      </div>
      <div className="xl:border-l xl:border-subtle xl:pl-8"><h2 className="flex items-center gap-2 text-[14px] font-semibold text-fg-primary"><ShieldCheck size={15} className="text-success"/>Stable API contract</h2><div className="mt-5 flex gap-10"><div><p className="text-2xl font-semibold text-fg-primary">v1</p><p className="mt-1 text-[11px] text-fg-muted">REST</p></div><div><p className="text-2xl font-semibold text-fg-primary">{pathCount}</p><p className="mt-1 text-[11px] text-fg-muted">OpenAPI paths</p></div><div><p className="text-2xl font-semibold text-fg-primary">{models.length}</p><p className="mt-1 text-[11px] text-fg-muted">Models</p></div></div><h3 className="mt-6 text-[12px] font-medium text-fg-secondary">Quick start</h3><pre className="mt-2 overflow-x-auto rounded-xl bg-field p-4 text-[11px] leading-5 text-fg-secondary">{example}</pre><button onClick={() => void navigator.clipboard.writeText(example)} className="ui-btn ui-btn-tertiary mt-2"><Copy size={12}/>Copy curl</button><h3 className="mt-6 text-[12px] font-medium text-fg-secondary">OpenAPI</h3><pre className="mt-2 max-h-[420px] overflow-auto rounded-xl bg-field p-4 text-[10px] leading-4 text-fg-muted">{openapi ? JSON.stringify(openapi,null,2) : "Loading…"}</pre></div>
    </section>

    <section className="ui-section"><div className="mb-4 flex items-end justify-between"><div><h2 className="ui-section-title">Issued credentials</h2><p className="ui-section-description">Inventory of service tokens and their current lifecycle state.</p></div><span className="text-[12px] text-fg-muted">{tokens.length} tokens</span></div><div className="overflow-x-auto border-y border-subtle"><table className="ui-table min-w-[850px]"><thead><tr><th>Name</th><th className="px-3">Prefix</th><th className="px-3">Scopes</th><th className="px-3">Models</th><th className="px-3">Limit</th><th className="px-3">Last used</th><th className="px-3">Expiry</th><th className="px-3"></th></tr></thead><tbody>{tokens.map((token) => <tr key={token.id}><td className="font-semibold text-fg-primary">{token.name}{token.revoked_at ? <span className="ui-badge ui-badge-danger ml-2">revoked</span> : null}</td><td className="px-3 font-mono text-[10px] text-fg-muted">{token.token_prefix}…</td><td className="max-w-72 px-3 text-[10px] text-fg-muted">{token.scopes.join(", ")}</td><td className="px-3 text-[10px] text-fg-muted">{token.allowed_models.length ? token.allowed_models.join(", ") : "all"}</td><td className="px-3 text-fg-muted">{token.rate_limit_per_minute}/min</td><td className="px-3 text-[10px] text-fg-muted">{fmt(token.last_used_at)}</td><td className="px-3 text-[10px] text-fg-muted">{fmt(token.expires_at)}</td><td className="px-3 text-right">{!token.revoked_at ? <button disabled={busy} onClick={() => void revoke(token.id)} className="ui-btn ui-btn-tertiary text-danger"><Trash2 size={11}/>Revoke</button> : null}</td></tr>)}{!loading && tokens.length === 0 ? <tr><td colSpan={8} className="py-10 text-center text-fg-muted">No API tokens issued.</td></tr> : null}</tbody></table></div></section>
  </div></AdminLayout>;
}
