events {}
http {
  server {
    listen 8000;
    client_max_body_size 50m;

    location /rest/v1/ {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header apikey $http_apikey;
      rewrite ^/rest/v1/(.*)$ /$1 break;
      proxy_pass http://rest:3000;
    }

    location /auth/v1/ {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Authorization $http_authorization;
      proxy_set_header apikey $http_apikey;
      rewrite ^/auth/v1/(.*)$ /$1 break;
      proxy_pass http://auth:9999;
    }

    location / {
      return 404;
    }
  }
}
