"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { ImagePlus, Loader2, Upload, X } from "lucide-react";
type Asset = { id: string; filename: string; mime_type: string; alt_text: string | null; preview_url: string };
export default function AssetPicker({ value, onChange }: { value: unknown; onChange: (value: string) => void }) {
  const [assets, setAssets] = useState<Asset[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const res = await fetch("/api/assets"); const body = await res.json(); if (!res.ok) throw new Error(body.error); setAssets(body.data || []); } catch (err) { setError(err instanceof Error ? err.message : "Could not load media"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(""); try { const form = new FormData(); form.set("file", file); form.set("folder", "content"); form.set("altText", file.name.replace(/\.[^.]+$/, "")); const res = await fetch("/api/assets", { method: "POST", body: form }); const body = await res.json(); if (!res.ok) throw new Error(body.error); await load(); onChange(body.data.id); } catch (err) { setError(err instanceof Error ? err.message : "Upload failed"); } finally { setUploading(false); } };
  const selected = assets.find((asset) => asset.id === value);
  return <div className="rounded-xl border border-default bg-field p-3">{selected ? <div className="flex items-center gap-3"><img src={selected.preview_url} alt={selected.alt_text || selected.filename} className="h-14 w-14 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-fg-primary">{selected.filename}</p><p className="mt-1 font-mono text-[10px] text-fg-muted">asset:{selected.id.slice(0, 8)}</p></div><button type="button" onClick={() => onChange("")} className="p-2 text-fg-muted hover:text-danger"><X size={15} /></button></div> : <div className="grid grid-cols-3 gap-2">{loading ? <div className="col-span-3 flex items-center justify-center py-4 text-fg-muted"><Loader2 size={16} className="animate-spin" /></div> : assets.slice(0, 6).map((asset) => <button type="button" key={asset.id} onClick={() => onChange(asset.id)} className="group overflow-hidden rounded-lg border border-subtle bg-surface-2 text-left hover:border-action/35"><img src={asset.preview_url} alt={asset.alt_text || asset.filename} className="h-16 w-full object-cover opacity-70 transition-opacity group-hover:opacity-100" /><span className="block truncate px-2 py-1.5 text-[10px] text-fg-muted">{asset.filename}</span></button>)}<label className="flex min-h-20 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-action/25 text-action hover:bg-action/5"><input type="file" className="hidden" onChange={upload} accept="image/*,video/*,.pdf" /><>{uploading ? <Loader2 size={17} className="animate-spin" /> : <><ImagePlus size={17} /><span className="mt-1 text-[9px] font-bold uppercase">Upload</span></>}</></label></div>}{error && <p className="mt-2 text-xs text-danger">{error}</p>}</div>;
}
