/** Phase 9 — Assurance & Discoverability live database certification. */
import { randomUUID } from "node:crypto";
import { createPgClient, createDisposableWorkspace, createAuthenticatedActor, teardownCertification } from "./cert-harness.mjs";

const client=await createPgClient();let workspaceId=null;let secondWorkspaceId=null;const authUserIds=[];const adminUserIds=[];
const assert=(c,m)=>{if(!c)throw new Error(m);};
async function expectFailure(label,fn,contains){try{await fn();throw new Error(`${label}: unexpectedly succeeded`);}catch(e){if(String(e.message).includes('unexpectedly succeeded'))throw e;if(contains&&!String(e.message).toLowerCase().includes(contains.toLowerCase()))throw new Error(`${label}: wrong error: ${e.message}`);console.log(`[PASS] ${label}: rejected as expected (${e.message})`);}}
async function createModel(actorId,name="P9 Page"){
 const api=`p9_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;const schema={name,apiKey:api,capability:"publishable",fields:[{key:"title",label:"Title",type:"text",required:true,localized:false,unique:false},{key:"internal_link",label:"Internal link",type:"url",required:false,localized:false,unique:false},{key:"hero_image",label:"Hero image",type:"media",required:false,localized:false,unique:false},{key:"meta_description",label:"Meta description",type:"long_text",required:false,localized:false,unique:false},{key:"schema_org",label:"Schema",type:"json",required:false,localized:false,unique:false}]};
 const {rows}=await client.query(`insert into content_models(workspace_id,name,api_key,status,current_schema_version,settings_json,created_by) values($1,$2,$3,'active',1,'{"capability":"publishable"}'::jsonb,$4) returning id`,[workspaceId,name,api,actorId]);const id=rows[0].id;await client.query(`insert into content_model_versions(content_model_id,version_number,schema_json,schema_hash,change_summary,created_by) values($1,1,$2::jsonb,$3,'p9 cert',$4)`,[id,JSON.stringify(schema),randomUUID(),actorId]);return {id,schema};
}
async function insertEntry(modelId,actorId,{status="approved",locale="en",title="Entry",published=false}={}){
 const {rows:[e]}=await client.query(`insert into content_entries(workspace_id,content_model_id,status,created_by,updated_by) values($1,$2,$3,$4,$4) returning id`,[workspaceId,modelId,status,actorId]);
 const state=published?'published':status==='approved'?'approved':'draft';const {rows:[v]}=await client.query(`insert into content_entry_versions(entry_id,model_schema_version,version_number,data_jsonb,locale,state,created_by,change_summary) values($1,1,1,jsonb_build_object('title',$2::text),$3,$4,$5,'p9 fixture') returning id`,[e.id,title,locale,state,actorId]);
 await client.query(`update content_entries set current_draft_version_id=$2::uuid,published_version_id=case when $3::boolean then $2::uuid else null::uuid end where id=$1`,[e.id,v.id,published]);return {entryId:e.id,versionId:v.id};
}
try{
 console.log("=== PHASE 9 LIVE DATABASE CERTIFICATION ===");
 const ws=await createDisposableWorkspace(client,"p9-live");workspaceId=ws.id;const actor=await createAuthenticatedActor(client,workspaceId,{role:"admin",permissions:["workspace.manage","content.entry.read","content.entry.create","content.entry.edit","content.entry.publish","routing.read","routing.manage"],emailPrefix:"p9-live"});authUserIds.push(actor.authUserId);adminUserIds.push(actor.adminUserId);
 const ws2=await createDisposableWorkspace(client,"p9-other");secondWorkspaceId=ws2.id;
 console.log(`[SETUP] Disposable workspace ${workspaceId}`);

 console.log("\n--- 1. RPC privilege boundary ---");
 const names=['cms_upsert_web_quality_policy','cms_update_route_discoverability','cms_refresh_redirect_dependencies','cms_refresh_translation_dependencies','cms_refresh_release_dependencies'];
 const {rows:acls}=await client.query(`select proname,proacl::text acl from pg_proc where proname=any($1::text[])`,[names]);
 assert(acls.length===names.length,"One or more Phase 9 RPCs missing");for(const r of acls){const parts=String(r.acl||'').replace(/^\{|\}$/g,'').split(',').filter(Boolean);assert(!parts.some(p=>p.startsWith('=')),`${r.proname} grants PUBLIC execute`);assert(!parts.some(p=>p.startsWith('anon=')||p.startsWith('authenticated=')),`${r.proname} grants browser role execute`);}console.log("[PASS] Phase 9 RPCs are service-bound.");

 console.log("\n--- 2. Web Quality policy atomicity ---");
 await client.query(`select cms_upsert_web_quality_policy($1,$2,'https://example.test','P9 Site','| Test',true,true,true,true,true,'{"default":"allow","GPTBot":"disallow"}'::jsonb,'{"maxImageBytes":1000000,"lcpWarningBytes":500000,"minLcpWidth":1200,"preferredImageFormats":["image/webp"]}'::jsonb,'{"warnNoindexOnCanonical":true,"requireHreflangForRequiredLocales":true}'::jsonb)`,[workspaceId,actor.adminUserId]);
 const {rows:[policy]}=await client.query(`select * from web_quality_policies where workspace_id=$1`,[workspaceId]);assert(policy.site_base_url==='https://example.test'&&policy.require_social_card&&policy.require_schema_org,"Policy did not persist");const {rows:[auditBefore]}=await client.query(`select count(*)::int c from platform_audit_events where workspace_id=$1 and action='assurance.web_quality_policy_saved'`,[workspaceId]);
 await expectFailure("Invalid site base URL",()=>client.query(`select cms_upsert_web_quality_policy($1,$2,'not a url','x',null,true,true,true,false,false,'{}','{}','{}')`,[workspaceId,actor.adminUserId]),"siteBaseUrl");const {rows:[auditAfter]}=await client.query(`select count(*)::int c from platform_audit_events where workspace_id=$1 and action='assurance.web_quality_policy_saved'`,[workspaceId]);assert(auditAfter.c===auditBefore.c,"Invalid policy leaked audit event");console.log("[PASS] Policy mutation and failed-mutation audit rollback certified.");

 console.log("\n--- 3. Route discoverability atomicity ---");
 const model=await createModel(actor.adminUserId);const base=await insertEntry(model.id,actor.adminUserId,{published:true,status:"published"});const {rows:[route]}=await client.query(`insert into content_routes(workspace_id,entry_id,locale,path,title,is_canonical,status) values($1,$2,'en','/p9-page','P9 Page',true,'active') returning *`,[workspaceId,base.entryId]);await client.query(`select cms_update_route_discoverability($1,$2,$3,'noindex',false,0.7,'weekly')`,[workspaceId,actor.adminUserId,route.id]);const {rows:[r1]}=await client.query(`select indexing_policy,sitemap_included,sitemap_priority,sitemap_changefreq from content_routes where id=$1`,[route.id]);assert(r1.indexing_policy==='noindex'&&!r1.sitemap_included&&Number(r1.sitemap_priority)===0.7,"Route discoverability update failed");const {rows:[routeAuditBefore]}=await client.query(`select count(*)::int c from platform_audit_events where workspace_id=$1 and action='assurance.route_discoverability_updated'`,[workspaceId]);await expectFailure("Invalid sitemap priority",()=>client.query(`select cms_update_route_discoverability($1,$2,$3,'index',true,1.5,'daily')`,[workspaceId,actor.adminUserId,route.id]),"priority");const {rows:[unchanged]}=await client.query(`select indexing_policy,sitemap_priority from content_routes where id=$1`,[route.id]);assert(unchanged.indexing_policy==='noindex'&&Number(unchanged.sitemap_priority)===0.7,"Invalid route mutation partially changed row");const {rows:[routeAuditAfter]}=await client.query(`select count(*)::int c from platform_audit_events where workspace_id=$1 and action='assurance.route_discoverability_updated'`,[workspaceId]);assert(routeAuditAfter.c===routeAuditBefore.c,"Invalid route mutation leaked audit");console.log("[PASS] Route indexing/sitemap policy and rollback certified.");

 console.log("\n--- 4. Atomic entry graph: entry + asset + route targets ---");
 const target=await insertEntry(model.id,actor.adminUserId,{published:true,status:"published",title:"Target"});const {rows:[targetRoute]}=await client.query(`insert into content_routes(workspace_id,entry_id,locale,path,title,is_canonical,status) values($1,$2,'en','/target','Target',true,'active') returning id`,[workspaceId,target.entryId]);const {rows:[asset]}=await client.query(`insert into assets(workspace_id,storage_provider,storage_key,filename,mime_type,size_bytes,width,height,checksum,alt_text,created_by) values($1,'local','p9/hero.webp','hero.webp','image/webp',400000,1600,900,$3,'Hero',$2) returning id`,[workspaceId,actor.adminUserId,randomUUID()]);
 const payload=[{fieldKey:"related",targetEntityType:"entry",targetEntryId:target.entryId,relationType:"reference"},{fieldKey:"hero_image",targetEntityType:"asset",targetAssetId:asset.id,relationType:"media_asset"},{fieldKey:"internal_link",targetEntityType:"route",targetRouteId:targetRoute.id,relationType:"internal_link"}];const {rows:[created]}=await client.query(`select cms_create_content_entry($1,$2,$3,$4::jsonb,'en','graph cert','[]'::jsonb,$5::jsonb,'Graph cert') data`,[workspaceId,actor.adminUserId,model.id,JSON.stringify({title:"Graph cert",hero_image:asset.id,internal_link:"/target"}),JSON.stringify(payload)]);const createdEntry=created.data.entry.id,createdVersion=created.data.version.id;const {rows:edges}=await client.query(`select target_entity_type,relation_type from content_relations where source_entry_id=$1 and source_version_id=$2 order by target_entity_type`,[createdEntry,createdVersion]);assert(edges.length===3&&new Set(edges.map(e=>e.target_entity_type)).size===3,"Atomic entry graph did not contain exact three target types");
 const {rows:[foreignAsset]}=await client.query(`insert into assets(workspace_id,storage_provider,storage_key,filename,mime_type,size_bytes,checksum) values($1,'local',$2,'x.webp','image/webp',1,$3) returning id`,[secondWorkspaceId,`x-${randomUUID()}`,randomUUID()]);const {rows:[entryCountBefore]}=await client.query(`select count(*)::int c from content_entries where workspace_id=$1`,[workspaceId]);const {rows:[createAuditBefore]}=await client.query(`select count(*)::int c from platform_audit_events where workspace_id=$1 and action='content.entry.created'`,[workspaceId]);await expectFailure("Cross-workspace asset graph injection",()=>client.query(`select cms_create_content_entry($1,$2,$3,$4::jsonb,'en','bad graph','[]'::jsonb,$5::jsonb,'Bad')`,[workspaceId,actor.adminUserId,model.id,JSON.stringify({title:"Bad"}),JSON.stringify([{fieldKey:"hero",targetEntityType:"asset",targetAssetId:foreignAsset.id,relationType:"media_asset"}])]),"foreign key");const {rows:[entryCountAfter]}=await client.query(`select count(*)::int c from content_entries where workspace_id=$1`,[workspaceId]);const {rows:[createAuditAfter]}=await client.query(`select count(*)::int c from platform_audit_events where workspace_id=$1 and action='content.entry.created'`,[workspaceId]);assert(entryCountAfter.c===entryCountBefore.c&&createAuditAfter.c===createAuditBefore.c,"Failed graph create leaked entry/audit state");console.log("[PASS] Entry+asset+route edges commit atomically; cross-workspace failure leaves no entry/version/audit residue.");

 console.log("\n--- 5. Redirect graph synchronization ---");
 const {rows:[redirect]}=await client.query(`insert into content_redirects(workspace_id,locale,source_path,target_path,status_code,is_active,created_by) values($1,'en','/old-target','/target',301,true,$2) returning id`,[workspaceId,actor.adminUserId]);let {rows:redges}=await client.query(`select target_route_id,relation_type from content_relations where source_redirect_id=$1`,[redirect.id]);assert(redges.length===1&&redges[0].target_route_id===targetRoute.id,"Redirect route edge missing");await client.query(`update content_redirects set target_path='https://external.test',updated_at=now() where id=$1`,[redirect.id]);({rows:redges}=await client.query(`select id from content_relations where source_redirect_id=$1`,[redirect.id]));assert(redges.length===0,"External redirect retained managed route edge");console.log("[PASS] Redirect graph auto-add/remove certified.");

 console.log("\n--- 6. Translation graph + workspace isolation ---");
 const translated=await insertEntry(model.id,actor.adminUserId,{status:"approved",locale:"de",title:"Deutsch"});const {rows:[tr]}=await client.query(`insert into content_entry_translations(workspace_id,source_entry_id,locale,translated_entry_id,source_version_id,reviewed_at) values($1,$2,'de',$3,$4,now()) returning id`,[workspaceId,target.entryId,translated.entryId,target.versionId]);const {rows:tedges}=await client.query(`select relation_type,target_entry_id from content_relations where source_translation_id=$1 order by relation_type`,[tr.id]);assert(tedges.length===2&&new Set(tedges.map(e=>e.relation_type)).has('translation_source')&&new Set(tedges.map(e=>e.relation_type)).has('translation_target'),"Translation graph incomplete");await expectFailure("Cross-workspace entry/model binding",()=>client.query(`insert into content_entries(workspace_id,content_model_id,status) values($1,$2,'draft')`,[secondWorkspaceId,model.id]),"foreign key");const {rows:[foreignModel]}=await client.query(`insert into content_models(workspace_id,name,api_key,status,current_schema_version) values($1,'Other',$2,'active',0) returning id`,[secondWorkspaceId,`other_${Date.now()}`]);const {rows:[foreignEntry]}=await client.query(`insert into content_entries(workspace_id,content_model_id,status) values($1,$2,'draft') returning id`,[secondWorkspaceId,foreignModel.id]);
 await expectFailure("Cross-workspace translation target",()=>client.query(`insert into content_entry_translations(workspace_id,source_entry_id,locale,translated_entry_id) values($1,$2,'fr',$3)`,[workspaceId,target.entryId,foreignEntry.id]),"foreign key");console.log("[PASS] Translation source/target edges and workspace integrity certified.");

 console.log("\n--- 7. Release target graph synchronization ---");
 await client.query(`insert into workspace_locales(workspace_id,locale,enabled,required,is_default) values($1,'en',true,true,true) on conflict (workspace_id,locale) do update set enabled=true,required=true,is_default=true`,[workspaceId]); const releaseEntry=await insertEntry(model.id,actor.adminUserId,{status:"approved",locale:"en",title:"Release Entry"});const {rows:[releaseRoute]}=await client.query(`insert into content_routes(workspace_id,entry_id,locale,path,title,is_canonical,status) values($1,$2,'en','/release-entry','Release Entry',true,'active') returning id`,[workspaceId,releaseEntry.entryId]);const {rows:[release]}=await client.query(`insert into releases(workspace_id,name,status,created_by,updated_by) values($1,'P9 Graph Release','draft',$2,$2) returning id`,[workspaceId,actor.adminUserId]);await client.query(`insert into release_items(release_id,entry_id,entry_version_id) values($1,$2,$3)`,[release.id,releaseEntry.entryId,releaseEntry.versionId]);await client.query(`insert into release_locale_targets(release_id,workspace_id,locale,required) values($1,$2,'en',true)`,[release.id,workspaceId]);const {rows:releaseEdges}=await client.query(`select target_entity_type,target_entry_id,target_route_id,relation_type from content_relations where source_release_id=$1 order by target_entity_type`,[release.id]);assert(releaseEdges.some(e=>e.relation_type==='release_entry'&&e.target_entry_id===releaseEntry.entryId),"Release→entry edge missing");assert(releaseEdges.some(e=>e.relation_type==='release_destination'&&e.target_route_id===releaseRoute.id),"Release→route edge missing");console.log("[PASS] Release entry/destination graph certified.");

 console.log("\n--- 8. Exactly-one-source graph invariant ---");
 await expectFailure("Multiple graph origins",()=>client.query(`insert into content_relations(workspace_id,source_route_id,source_release_id,source_entity_type,target_entity_type,relation_type,target_entry_id) values($1,$2,$3,'route','entry','bad',$4)`,[workspaceId,targetRoute.id,release.id,target.entryId]),"check");console.log("[PASS] Exactly-one-source invariant preserved with Phase 9 origins.");
 console.log("\nPHASE 9 LIVE DATABASE CERTIFICATION: ALL PASSED");
} finally {
 if(workspaceId){await client.query(`delete from releases where workspace_id=$1`,[workspaceId]).catch(()=>{});await client.query(`delete from content_entries where workspace_id=$1`,[workspaceId]).catch(()=>{});await client.query(`delete from content_models where workspace_id=$1`,[workspaceId]).catch(()=>{});}
 await teardownCertification({client,workspaceId,authUserIds,adminUserIds});
 if(secondWorkspaceId){await client.query(`delete from content_entries where workspace_id=$1`,[secondWorkspaceId]).catch(()=>{});await client.query(`delete from content_models where workspace_id=$1`,[secondWorkspaceId]).catch(()=>{});await client.query(`delete from workspaces where id=$1`,[secondWorkspaceId]).catch(()=>{});}
 await client.end();
}
