#!/usr/bin/env node
import { createHmac, randomBytes } from 'node:crypto';
import { execFile, spawn } from 'node:child_process';
import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import os from 'node:os';import path from 'node:path';import { promisify } from 'node:util';
const execFileAsync=promisify(execFile),composeFile=path.resolve(process.cwd(),'deploy/local/docker-compose.yml');
const b64=v=>Buffer.from(v).toString('base64url');const jwt=(secret,role)=>{const now=Math.floor(Date.now()/1000),h=b64(JSON.stringify({alg:'HS256',typ:'JWT'})),p=b64(JSON.stringify({iss:'supabase',ref:'local',role,iat:now,exp:2147483647})),s=createHmac('sha256',secret).update(`${h}.${p}`).digest('base64url');return`${h}.${p}.${s}`};const q=v=>`"${v.replace(/\\/g,'/').replace(/"/g,'\\"')}"`;
const allowed=()=>process.env.POLYNOVEA_LOCAL_RUNTIME_CONTROL==='1';
async function init(directory){if(!allowed())throw new Error('Set POLYNOVEA_LOCAL_RUNTIME_CONTROL=1 to enable local runtime control.');const root=path.resolve(directory||path.join(os.homedir(),'PolynoveaCMS'));await mkdir(path.join(root,'postgres'),{recursive:true});await mkdir(path.join(root,'backups'),{recursive:true});const envFile=path.join(root,'runtime.env');let exists=true;try{await access(envFile,constants.F_OK)}catch{exists=false}if(!exists){const pw=randomBytes(24).toString('base64url'),secret=randomBytes(48).toString('base64url'),enc=randomBytes(32).toString('base64'),anon=jwt(secret,'anon'),service=jwt(secret,'service_role'),app=Number(process.env.POLYNOVEA_LOCAL_APP_PORT||3210),sb=Number(process.env.POLYNOVEA_LOCAL_SUPABASE_PORT||54321);await writeFile(envFile,[`POLYNOVEA_DATA_DIR=${q(root)}`,`POLYNOVEA_APP_PORT=${app}`,`POLYNOVEA_SUPABASE_PORT=${sb}`,`POSTGRES_PASSWORD=${q(pw)}`,`JWT_SECRET=${q(secret)}`,`ANON_KEY=${q(anon)}`,`SERVICE_ROLE_KEY=${q(service)}`,`CMS_CONFIG_ENCRYPTION_KEY=${q(enc)}`,'R2_S3_ENDPOINT=','R2_ACCESS_KEY_ID=','R2_SECRET_ACCESS_KEY=','R2_BUCKET_NAME=media','R2_PUBLIC_URL='].join('\n')+'\n',{mode:0o600})}return{directory:root,envFile}}
const args=(cfg,a)=>['compose','--env-file',cfg.envFile,'-f',composeFile,...a];async function docker(cfg,a){const r=await execFileAsync('docker',args(cfg,a),{windowsHide:true,maxBuffer:10*1024*1024});return{stdout:r.stdout.trim(),stderr:r.stderr.trim()}}
async function action(cmd,directory){const cfg=await init(directory);if(cmd==='start')return{...cfg,...await docker(cfg,['up','-d','--build'])};if(cmd==='stop')return{...cfg,...await docker(cfg,['down'])};if(cmd==='upgrade'){await docker(cfg,['pull']);return{...cfg,...await docker(cfg,['up','-d','--build'])}}return{...cfg,...await docker(cfg,['ps','--format','json'])}}
async function backup(directory){const cfg=await init(directory),file=path.join(cfg.directory,'backups',`polynovea-${new Date().toISOString().replace(/[:.]/g,'-')}.sql`);await new Promise((resolve,reject)=>{const child=spawn('docker',args(cfg,['exec','-T','db','pg_dump','-U','postgres','-d','postgres','--no-owner','--no-privileges']),{stdio:['ignore','pipe','pipe'],windowsHide:true}),out=[],err=[];child.stdout.on('data',c=>out.push(Buffer.from(c)));child.stderr.on('data',c=>err.push(Buffer.from(c)));child.on('error',reject);child.on('close',async code=>{if(code)return reject(new Error(Buffer.concat(err).toString()||`pg_dump exited ${code}`));await writeFile(file,Buffer.concat(out),{mode:0o600});resolve()})});return{file,createdAt:new Date().toISOString()}}
async function restore(directory,file){const cfg=await init(directory),resolved=path.resolve(file),backupRoot=path.resolve(cfg.directory,'backups');if(!resolved.startsWith(backupRoot))throw new Error('Backup must be inside the local workspace backups directory');const bytes=await readFile(resolved);await new Promise((resolve,reject)=>{const child=spawn('docker',args(cfg,['exec','-T','db','psql','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1']),{stdio:['pipe','ignore','pipe'],windowsHide:true}),err=[];child.stderr.on('data',c=>err.push(Buffer.from(c)));child.on('error',reject);child.on('close',code=>code?reject(new Error(Buffer.concat(err).toString()||`psql exited ${code}`)):resolve());child.stdin.end(bytes)});return{restored:true,file:resolved}}
const argv=process.argv.slice(2),command=argv[0]||'status',directory=argv.find(v=>v.startsWith('--directory='))?.slice(12)||null;try{let result;if(command==='init')result=await init(directory);else if(['start','stop','status','upgrade'].includes(command))result=await action(command,directory);else if(command==='backup')result=await backup(directory);else if(command==='restore'){const file=argv.slice(1).find(v=>!v.startsWith('--'));if(!file)throw new Error('restore requires a backup file');result=await restore(directory,file)}else throw new Error('Usage: local-runtime.mjs init|start|stop|status|backup|restore <file>|upgrade [--directory=/path]');console.log(JSON.stringify(result,null,2))}catch(error){console.error(error instanceof Error?error.message:String(error));process.exit(1)}
