-- Baseline migration — snapshot of supabase/migration.sql as of 2026-09-01.
--
-- This file is a verbatim copy of the hand-run script the project used before
-- migration discipline existed (see ../../docs/upgrade/MIGRATIONS.md). It is
-- captured here, unmodified, so that version history starts from an accurate
-- record of what has already been applied to the production database.
--
-- Do not edit this file. Schema changes from this point forward go in new,
-- numbered files in this directory (0002_*.sql, 0003_*.sql, ...).

-- Polynovea Admin — CMS Tables
-- Run this in: Supabase Dashboard → SQL Editor → New Query → Run

-- Live Events
create table if not exists live_events (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  date text not null,
  time text,
  venue text not null,
  city text not null,
  capacity text,
  status text,
  description text,
  cta text,
  href text,
  youtube_url text,
  status_type text check (status_type in ('active', 'progress', 'planned')) default 'planned',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Past Shows
create table if not exists past_shows (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  date text not null,
  time text,
  venue text not null,
  city text not null,
  capacity text,
  status text,
  description text,
  cta text,
  href text,
  youtube_url text,
  status_type text check (status_type in ('active', 'progress', 'planned')) default 'planned',
  attendance integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Venue Partnerships
create table if not exists venue_partnerships (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  city text not null,
  capacity text,
  type text,
  description text,
  contact_email text,
  logo_url text,
  contact_status text,
  status_type text check (status_type in ('active', 'progress', 'planned')) default 'planned',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Blog Posts
create table if not exists blog_posts (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  slug text not null unique,
  content text,
  excerpt text,
  author text,
  status text check (status in ('draft', 'published')) default 'draft',
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Live Metrics
create table if not exists live_metrics (
  id serial primary key,
  label text not null,
  value text not null,
  period text,
  trend text,
  trend_direction text check (trend_direction in ('up', 'down')) default 'up'
);

-- Disable RLS for now (private admin panel, no public access)
alter table live_events disable row level security;
alter table past_shows disable row level security;
alter table venue_partnerships disable row level security;
alter table blog_posts disable row level security;
alter table live_metrics disable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- Content Module Tables (added — run if missing)
-- ─────────────────────────────────────────────────────────────────────────────

-- Social Posts (Content Library)
create table if not exists social_posts (
  id uuid default gen_random_uuid() primary key,
  entity text not null,                        -- 'polynovea'
  venue_id text,                               -- place_id from RDS venues (nullable)
  title text not null,
  platform text not null,                      -- Instagram | YouTube | Facebook | etc.
  type text not null,                          -- Reel | Short | Video | Post | Story | Article | Ad
  posted date not null,
  views integer,
  status text check (status in ('draft', 'published')) default 'published',
  checkpoints text[] default array['future','future','future','future'],
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists social_posts_entity_idx  on social_posts(entity);
create index if not exists social_posts_venue_idx   on social_posts(venue_id);
create index if not exists social_posts_posted_idx  on social_posts(posted desc);

alter table social_posts disable row level security;

-- Ad Campaigns (Ads Dashboard)
create table if not exists ad_campaigns (
  id uuid default gen_random_uuid() primary key,
  entity text not null,                        -- 'polynovea'
  venue_id text,                               -- place_id from RDS venues (nullable)
  campaign text not null,
  platform text not null,                      -- Meta Ads | Google Ads | LinkedIn Ads
  objective text not null,                     -- Awareness | Reach | Engagement | Conversions
  budget numeric(12,2) default 0,
  spend numeric(12,2) default 0,
  ctr numeric(6,2) default 0,
  conversions integer default 0,
  status text check (status in ('ACTIVE','COMPLETED','PAUSED')) default 'ACTIVE',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ad_campaigns_entity_idx on ad_campaigns(entity);
create index if not exists ad_campaigns_venue_idx  on ad_campaigns(venue_id);
create index if not exists ad_campaigns_status_idx on ad_campaigns(status);

alter table ad_campaigns disable row level security;

-- Platforms (dynamic platform list for Content Library + Ads Dashboard)
create table if not exists platforms (
  id uuid default gen_random_uuid() primary key,
  name text not null unique,
  for_social boolean not null default true,
  for_ads boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists platforms_active_idx on platforms(is_active);

alter table platforms disable row level security;

insert into platforms (name, for_social, for_ads, sort_order) values
  ('Instagram', true, false, 0),
  ('YouTube', true, false, 1),
  ('Facebook', true, false, 2),
  ('Threads', true, false, 3),
  ('LinkedIn', true, false, 4),
  ('Twitter / X', true, false, 5),
  ('Meta Ads', true, true, 6),
  ('Google Ads', true, true, 7),
  ('LinkedIn Ads', false, true, 8)
on conflict (name) do nothing;

-- Admin Users / Access Control
create table if not exists admin_users (
  id uuid default gen_random_uuid() primary key,
  auth_user_id uuid,
  username text not null unique,
  email text not null unique,
  display_name text,
  role text check (role in ('master', 'admin', 'editor', 'viewer')) default 'viewer',
  is_active boolean default true,
  surface_access text[] default array['cms', 'content'],
  module_access text[] default array[]::text[],
  module_write_access text[] default array[]::text[],
  created_by text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table admin_users add column if not exists module_write_access text[] default array[]::text[];

create index if not exists admin_users_username_idx on admin_users(username);
create index if not exists admin_users_email_idx on admin_users(email);
create index if not exists admin_users_role_idx on admin_users(role);

alter table admin_users disable row level security;

create table if not exists admin_activity_log (
  id uuid default gen_random_uuid() primary key,
  actor_email text not null,
  actor_username text,
  actor_role text,
  action text not null,
  target_type text not null,
  target_id text,
  target_label text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists admin_activity_log_created_at_idx on admin_activity_log(created_at desc);
create index if not exists admin_activity_log_target_type_idx on admin_activity_log(target_type);

alter table admin_activity_log disable row level security;
