import { requireDeveloperApi, developerModelAllowed } from "@/lib/developer/apiAuth";
import { apiError, apiSuccess } from "@/lib/developer/apiContract";
import { getEntryDeveloperView } from "@/lib/developer/resourceService";
import { archiveEntry, saveDraft } from "@/lib/content/entryService";
import { logDeveloperApiMutation } from "@/lib/developer/developerAudit";

export async function GET(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireDeveloperApi(req,{scope:"content.read"});if(auth.error)return auth.error;const {id}=await params;const view=await getEntryDeveloperView(auth.data!.workspaceId,id);if(!view)return apiError("ENTRY_NOT_FOUND","Content entry not found",404,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});if(!developerModelAllowed(auth.data!,view.model.apiKey))return apiError("MODEL_RESTRICTED","Token is not permitted to access this content model",403,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});return apiSuccess(view,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}
export async function PUT(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireDeveloperApi(req,{scope:"content.write",requireActor:true});if(auth.error)return auth.error;const {id}=await params;const view=await getEntryDeveloperView(auth.data!.workspaceId,id);if(!view)return apiError("ENTRY_NOT_FOUND","Content entry not found",404,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});if(!developerModelAllowed(auth.data!,view.model.apiKey))return apiError("MODEL_RESTRICTED","Token is not permitted to access this content model",403,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});try{const body=await req.json();const result=await saveDraft({workspaceId:auth.data!.workspaceId,entryId:id,data:body.data&&typeof body.data==="object"?body.data:{},locale:body.locale,actorAdminUserId:auth.data!.actorAdminUserId!,changeSummary:body.changeSummary||"Updated through Developer API",expectedVersionNumber:body.expectedVersionNumber===undefined?undefined:Number(body.expectedVersionNumber)});if(!result.ok)return apiError("ENTRY_UPDATE_FAILED",result.error,result.status,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit,details:"conflict" in result?result.conflict:undefined});await logDeveloperApiMutation(auth.data!,"developer.entry.updated","content_entry",id,{model:view.model.apiKey,versionId:result.data.version.id,versionNumber:result.data.version.version_number});return apiSuccess(result.data,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}catch(e){return apiError("ENTRY_UPDATE_FAILED",e instanceof Error?e.message:"Could not update entry",400,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}}
export async function DELETE(req:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireDeveloperApi(req,{scope:"content.delete",requireActor:true});if(auth.error)return auth.error;const {id}=await params;const view=await getEntryDeveloperView(auth.data!.workspaceId,id);if(!view)return apiError("ENTRY_NOT_FOUND","Content entry not found",404,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});if(!developerModelAllowed(auth.data!,view.model.apiKey))return apiError("MODEL_RESTRICTED","Token is not permitted to access this content model",403,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});const result=await archiveEntry({workspaceId:auth.data!.workspaceId,entryId:id,actorAdminUserId:auth.data!.actorAdminUserId!});if(!result.ok)return apiError("ENTRY_ARCHIVE_FAILED",result.error,result.status,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});await logDeveloperApiMutation(auth.data!,"developer.entry.archived","content_entry",id,{model:view.model.apiKey});return apiSuccess(result.data,{requestId:auth.data!.requestId,rateLimit:auth.data!.rateLimit});}
